# Urine Data Analysis

With the cleaned and individually exported data, now the data is ready to be fine tuned and analysed. Urine data will be first analyzed before moving onto the blood lab analysis.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [4]:
current_directory = os.getcwd()
print(current_directory)

/Users/Rachel/Documents/GitHub/portfolio_ds_projects/NHANES_analysis

In [23]:
df_d = pd.read_csv('cleaned_demographics.csv')
df_a = pd.read_csv('cleaned_anthropometry.csv')
df_cr = pd.read_csv('urine_cr_alb.csv')

In [6]:
df_d.head()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty
0,109263.0,1.0,2.0,6.0,NaN,NaN,4.66
1,109264.0,2.0,13.0,1.0,NaN,NaN,0.83
2,109265.0,1.0,2.0,3.0,NaN,NaN,3.06
3,109266.0,2.0,29.0,6.0,5.0,3.0,5.00
4,109269.0,1.0,2.0,2.0,NaN,NaN,0.96

In [7]:
df_d.isna().sum()

participant_id              0
gender                      0
age_year                    0
race                        0
education_level          5756
marital_status           5756
family_income_poverty    1847
dtype: int64

In [11]:
df_d.describe()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty
count,14300.000000,14300.000000,14300.000000,14300.000000,8544.000000,8544.000000,12453.000000
mean,117068.670280,1.504545,33.861818,3.482797,3.554775,1.694640,2.385320
std,4501.643618,0.499997,25.162121,1.625440,1.210994,2.613598,1.625954
min,109263.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,113170.750000,1.000000,10.000000,3.000000,3.000000,1.000000,1.010000
50%,117081.500000,2.000000,31.000000,3.000000,4.000000,1.000000,1.940000
75%,120974.250000,2.000000,56.000000,4.000000,4.000000,2.000000,3.850000
max,124822.000000,2.000000,80.000000,7.000000,9.000000,99.000000,5.000000

Current data analysis will focus on adults aged 18 or older. Subjects that are younger than 18 will be removed.

In [18]:
adults = df_d[df_d['age_year'] >= 18]

In [19]:
adults.describe()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty
count,8965.000000,8965.000000,8965.000000,8965.000000,8544.000000,8544.000000,7705.000000
mean,117107.849637,1.513999,49.465142,3.484551,3.554775,1.694640,2.558740
std,4501.048325,0.499832,18.457564,1.574461,1.210994,2.613598,1.627623
min,109266.000000,1.000000,18.000000,1.000000,1.000000,1.000000,0.000000
25%,113211.000000,1.000000,33.000000,3.000000,3.000000,1.000000,1.170000
50%,117091.000000,2.000000,50.000000,3.000000,4.000000,1.000000,2.160000
75%,121022.000000,2.000000,64.000000,4.000000,4.000000,2.000000,4.140000
max,124822.000000,2.000000,80.000000,7.000000,9.000000,99.000000,5.000000

The next is anthropometry (body measures). First, the question is how much of the documented samples is considered obese. The BMI cutoffs are as follows:
 * less than 18 kg/m^2: underweight
 * 18-24.9 kg/m^2: normal weight
 * 25-29.9 kg/m^2: overweight
 * 30-39.9 kg/m^2: obese
 * greater than 40 kg/m^2: morbidly obese

In [8]:
df_a.isna().sum()

participant_id                 0
weight_kg                     32
weight_comment             13519
recumbent_length_cm        12637
standing_height              950
standing_height_comment    13936
bmi                          970
bmi_category_child          9358
upper_leg_cm                3123
upper_arm_cm                 617
arm_circumference_cm         623
waist_circ_cm               1533
hip_circ_cm                 4245
dtype: int64

Since this data analysis focuses on evaluating BMI, the subjects that are missing the BMI should be dropped. By joining the adults data frame with the anthropometry (in the next steps to come), subjects under the age 18 will automatically be removed.

In [27]:
df_a = df_a.dropna(subset=['bmi'])

In [28]:
df_a.isna().sum()

participant_id                 0
weight_kg                      0
weight_comment             12601
recumbent_length_cm        12571
standing_height                0
standing_height_comment    13038
bmi                            0
bmi_category_child          8388
upper_leg_cm                2177
upper_arm_cm                 460
arm_circumference_cm         461
waist_circ_cm                603
hip_circ_cm                 3296
dtype: int64

In [10]:
df_a.columns

Index(['participant_id', 'weight_kg', 'weight_comment', 'recumbent_length_cm',
       'standing_height', 'standing_height_comment', 'bmi',
       'bmi_category_child', 'upper_leg_cm', 'upper_arm_cm',
       'arm_circumference_cm', 'waist_circ_cm', 'hip_circ_cm'],
      dtype='object')

In [ ]:
df_a = df_a.drop(['