# Blood Lab Analysis

For the purposes of this project, the blood labs that could contribute to metabolism and metabolic syndrome will be analyzed. The blood labs of focus are as follows:

 * Cholesterol panel
 * CBC with differential
 * Glycohemoglobin (hemoglobin A1c)
 * Insulin
 * Fasting glucose
 * Sex hormones

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
os.getcwd()

'/Users/Rachel/Documents/GitHub/portfolio_ds_projects/NHANES_analysis'

In [4]:
df_ldl = pd.read_csv('tri_ldl_cleaned.csv')
df_hdl = pd.read_csv('hdl_cleaned.csv')
df_total = pd.read_csv('total_chol_cleaned.csv')
df_a = pd.read_csv('cleaned_anthropometry.csv')
df_d = pd.read_csv('cleaned_demographics.csv')

In [5]:
df = df_d.merge(df_a, on='participant_id')

In [11]:
df.head()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty,weight_kg,weight_comment,recumbent_length_cm,standing_height,standing_height_comment,bmi,bmi_category_child,upper_leg_cm,upper_arm_cm,arm_circumference_cm,waist_circ_cm,hip_circ_cm
0,109264.0,2.0,13.0,1.0,NaN,NaN,0.83,42.2,NaN,NaN,154.7,NaN,17.6,2.0,36.3,33.8,22.7,63.8,85.0
1,109265.0,1.0,2.0,3.0,NaN,NaN,3.06,12.0,NaN,91.6,89.3,NaN,15.0,2.0,NaN,18.6,14.8,41.2,NaN
2,109266.0,2.0,29.0,6.0,5.0,3.0,5.00,97.1,NaN,NaN,160.2,NaN,37.8,NaN,40.8,34.7,35.8,117.9,126.1
3,109269.0,1.0,2.0,2.0,NaN,NaN,0.96,13.6,NaN,90.9,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,109270.0,2.0,11.0,4.0,NaN,NaN,1.88,75.3,NaN,NaN,156.0,NaN,30.9,4.0,42.6,36.1,31.0,91.4,NaN

In [13]:
df.columns

Index(['participant_id', 'gender', 'age_year', 'race', 'education_level',
       'marital_status', 'family_income_poverty', 'weight_kg',
       'weight_comment', 'recumbent_length_cm', 'standing_height',
       'standing_height_comment', 'bmi', 'bmi_category_child', 'upper_leg_cm',
       'upper_arm_cm', 'arm_circumference_cm', 'waist_circ_cm', 'hip_circ_cm'],
      dtype='object')

In [14]:
df = df[['participant_id', 'gender', 'age_year', 'race', 'bmi']]

In [15]:
df_c = df.merge(df_ldl, on='participant_id')

In [16]:
df_c.head()

,participant_id,gender,age_year,race,bmi,Unnamed: 0,triglyceride_mg_dl,triglyceride_mmol_l,ldl_friedewald_mg_dl,ldl_friedwalkd_mmol_l,ldl_martin_hopkins_mg_dl,ldl_martin_hopkins_mmol_l,ldl_nih_mg_dl,ldl_nih_mmol_l
0,109264.0,2.0,13.0,1.0,17.6,0,40.0,0.452,86.0,2.224,82.0,2.121,85.0,2.198
1,109271.0,1.0,49.0,3.0,29.7,1,84.0,0.948,97.0,2.508,96.0,2.483,98.0,2.534
2,109274.0,1.0,68.0,7.0,30.2,2,133.0,1.502,49.0,1.267,54.0,1.396,52.0,1.345
3,109277.0,2.0,12.0,1.0,18.6,3,24.0,0.271,64.0,1.655,62.0,1.603,61.0,1.577
4,109282.0,1.0,76.0,3.0,26.6,4,132.0,1.490,164.0,4.241,163.0,4.215,166.0,4.293

In [17]:
df_c.columns

Index(['participant_id', 'gender', 'age_year', 'race', 'bmi', 'Unnamed: 0',
       'triglyceride_mg_dl', 'triglyceride_mmol_l', 'ldl_friedewald_mg_dl',
       'ldl_friedwalkd_mmol_l', 'ldl_martin_hopkins_mg_dl',
       'ldl_martin_hopkins_mmol_l', 'ldl_nih_mg_dl', 'ldl_nih_mmol_l'],
      dtype='object')

In [22]:
df_c = df_c.drop('Unnamed: 0', axis =1)

In [23]:
df_c = df_c.merge(df_hdl, on='participant_id')

In [24]:
df_c.columns

Index(['participant_id', 'gender', 'age_year', 'race', 'bmi',
       'triglyceride_mg_dl', 'triglyceride_mmol_l', 'ldl_friedewald_mg_dl',
       'ldl_friedwalkd_mmol_l', 'ldl_martin_hopkins_mg_dl',
       'ldl_martin_hopkins_mmol_l', 'ldl_nih_mg_dl', 'ldl_nih_mmol_l',
       'Unnamed: 0', 'direct_hdl_mg_dl', 'direct_hdl_mmol_l'],
      dtype='object')

In [25]:
df_c = df_c.drop('Unnamed: 0', axis =1)

In [26]:
df_c = df_c.merge(df_total, on='participant_id')

In [27]:
df_c.head()

,participant_id,gender,age_year,race,bmi,triglyceride_mg_dl,triglyceride_mmol_l,ldl_friedewald_mg_dl,ldl_friedwalkd_mmol_l,ldl_martin_hopkins_mg_dl,ldl_martin_hopkins_mmol_l,ldl_nih_mg_dl,ldl_nih_mmol_l,direct_hdl_mg_dl,direct_hdl_mmol_l,Unnamed: 0,total_cholesterol_mg_dl,total_cholesterol_mmol_l
0,109264.0,2.0,13.0,1.0,17.6,40.0,0.452,86.0,2.224,82.0,2.121,85.0,2.198,72.0,1.86,0,166.0,4.29
1,109271.0,1.0,49.0,3.0,29.7,84.0,0.948,97.0,2.508,96.0,2.483,98.0,2.534,33.0,0.85,3,147.0,3.80
2,109274.0,1.0,68.0,7.0,30.2,133.0,1.502,49.0,1.267,54.0,1.396,52.0,1.345,29.0,0.75,5,105.0,2.72
3,109277.0,2.0,12.0,1.0,18.6,24.0,0.271,64.0,1.655,62.0,1.603,61.0,1.577,60.0,1.55,7,129.0,3.34
4,109282.0,1.0,76.0,3.0,26.6,132.0,1.490,164.0,4.241,163.0,4.215,166.0,4.293,43.0,1.11,10,233.0,6.03

In [28]:
df_c.columns

Index(['participant_id', 'gender', 'age_year', 'race', 'bmi',
       'triglyceride_mg_dl', 'triglyceride_mmol_l', 'ldl_friedewald_mg_dl',
       'ldl_friedwalkd_mmol_l', 'ldl_martin_hopkins_mg_dl',
       'ldl_martin_hopkins_mmol_l', 'ldl_nih_mg_dl', 'ldl_nih_mmol_l',
       'direct_hdl_mg_dl', 'direct_hdl_mmol_l', 'Unnamed: 0',
       'total_cholesterol_mg_dl', 'total_cholesterol_mmol_l'],
      dtype='object')

In [29]:
df_c = df_c.drop('Unnamed: 0', axis =1)

In [30]:
df_c.shape

(4598, 17)