## Sex Hormones

Sex hormones also affect how the body stores adiposity. Hormonal imbalance can cause varying effects on the human body. For example, female with polycystic ovarian syndrome (PCOS) have higher testosterone levels. They are more likely to be overweight compared to female with normal hormone balance. 

This analysis will evaluate how the sex hormones affect the BMI.

NHANES data includes the following sex hormones and their ranges as shown in their lab documentation unless otherwise indicated:

* **17-hydroxyprogesterone (17-OHP) (ng/dL)**: a steroid hormone produced by the adrenal glands and gonads, acting as a precursor to cortisol.
    * Males: 41 – 183 ng/dL
    * Females:
        * Follicular: 45 – 1185 ng/dL
        * Luteal: 42 – 450 ng/dL
        * Postmenopausal: 18 – 48 ng/dL
        
* **Androstenedione (ng/dL)**: a weak androgenic steroid hormone produced by the adrenal glands and gonads, acting as a direct precursor to testosterone and estrogen.
    * Males: 75 - 205 ng/dL
    * Females: 85 - 275 ng/dL

* **Progesterone (ng/dL)**
    * Males: 13 - 97 ng/dL
    * Females:
        * Follicular: 15 – 70
        * Luteal: 200 – 2500
        * Gestation:
            * First trimester: 1025 – 4400
            * Second trimester: 1950 – 8250
            * Third trimester: 6500 – 22,900

* **Testosterone (ng/dL)**
    * Males: 280 – 1100
    * Females: 15 – 70
        * Postemenopausal: 8 – 35

* **Anti-müllerian hormone (AMH)**: in the developing fetus, works to determine the sex of the fetus. In adult females, it can assess ovarian reserve. AMH ranges vary by age (the following values are provided by Cleveland Clinic and represent lower end of the spectrum for the ages):
    * 25 years old: 3.0 ng/mL.
    * 30 years old: 2.5 ng/mL.
    * 35 years old: 1.5 ng/ mL.
    * 40 years old: 1 ng/mL.
    * 45 years old: 0.5 ng/mL.

* **Estradiol (E2) (pg/mL)**: the primary and most potent form of estrogen in the human body
    * Adult males: 10-50 pg/mL
    * Adult females:
        * Early follicular phase: 20 - 150
        * Late follicular phase: 40-350 pg/mL
        * Midcycle peak: 150-750 pg/mL
        * Luteal phase: 30-450 pg/mL
        * Postmenopause: ≤ 20 pg/mL

* **Esterone (E1) (ng/dL)**: the primary form of estrogen that your body makes after menopause.
    * Males: 1.5 – 6.5
    * Females:
        * Early follicular phase: 1.5 – 15
        * Late follicular phase: 10 - 25
        * Luteal phase: 1.5 - 20
        * Postmenopausal: 1.5 - 5.5

* **Estriol (E3)**: primary form of estrogen during pregnancy

* **Esterone sulfate (pg/mL)**
    * Male: 230 - 2200
    * Female:
        * Follicular: 300 - 2600
        * Luteal: 100 - 3200
        * Postmenopausal: 100 - 1300

* **Dehydroepiandrosterone sulfate (DHEAS) (mcg/dL)**
    * Male:
        * 19 - 30 y/o: 125 - 619
        * 31 - 50 y/o: 59 - 452
        * 51 - 60 y/o: 20 - 413
        * 61 - 83 y/o: 10 - 285
    * Female:
        * 19 - 30 y/o: 29 - 781
        * 31 - 50 y/o: 12 - 379
        * Postemenopausal: 30 - 260

* **Follicle Stimulating Hormone (FSH)** from medline.gov
    * Adult male: 1.5 - 12.4 mIU/mL
    * Adult female: 4.7 - 21.5 mIU/mL
        * Postmenopausal: 25.8 - 134.8 mIU/mL

* **Luteinizing Hormong (LH)** from medline.gov
    * Adult male: 1.8 - 8.6 IU/L
    * Adult female: 5 - 25 IU/L
        * Postmenopausal: 7.7 - 58.5 IU/L

* **Sex Hormone Binding Globulin (SHBG) nmol/L** from LabCorp
    * Male:
        * 20-49 y/o: 16.5 - 55.9 
        * >49 y/o: 19.3 - 76.4
    * Female:
        * 20-49 y/o: 24.6 - 122
        * >49 y/o: 17.3 - 125

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
import os
import statsmodels.api as sm
import scipy.stats as stats
from math import erf, sqrt
from math import atanh, sqrt

In [2]:
df_d = pd.read_csv('cleaned_demographics.csv')
df_a = pd.read_csv('cleaned_anthropometry.csv')
df = pd.read_csv('sex_hormones.csv')

In [3]:
df = df_d.merge(df_a, on='participant_id').merge(df, on='participant_id')

In [4]:
df.head()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty,weight_kg,weight_comment,recumbent_length_cm,...,estrone_sulfate_comment_code,follicle_stimulating_hormone_miu_ml,fsh_comment_code,luteinizing_hormone_miu_ml,luteinizing_hormone_comment_code,progesterone_ng_dl,progesterone_nmol_l,progesterone_comment_code,shbg_nmol_l,shbg_comment_code
0,109266.0,2.0,29.0,6.0,5.0,3.0,5.00,97.1,NaN,NaN,...,NaN,7.15,0.0,4.55,0.0,1.500,0.0477,0.0,22.54,0.0
1,109270.0,2.0,11.0,4.0,NaN,NaN,1.88,75.3,NaN,NaN,...,0.0,4.87,0.0,3.64,0.0,0.608,0.0193,1.0,23.68,0.0
2,109271.0,1.0,49.0,3.0,2.0,3.0,NaN,98.8,NaN,NaN,...,0.0,8.30,0.0,18.86,0.0,8.770,0.2790,0.0,42.91,0.0
3,109273.0,1.0,36.0,3.0,4.0,3.0,0.83,74.3,NaN,NaN,...,0.0,3.33,0.0,4.22,0.0,16.000,0.5090,0.0,59.72,0.0
4,109274.0,1.0,68.0,7.0,4.0,3.0,1.20,103.7,NaN,NaN,...,0.0,5.14,0.0,9.47,0.0,4.110,0.1310,0.0,62.92,0.0

In [5]:
df.columns

Index(['participant_id', 'gender', 'age_year', 'race', 'education_level',
       'marital_status', 'family_income_poverty', 'weight_kg',
       'weight_comment', 'recumbent_length_cm', 'standing_height',
       'standing_height_comment', 'bmi', 'bmi_category_child', 'upper_leg_cm',
       'upper_arm_cm', 'arm_circumference_cm', 'waist_circ_cm', 'hip_circ_cm',
       'Unnamed: 0', '17α_hydroxyprogesterone_ng_dl',
       '17α_hydroxyprogesterone_nmol_l',
       '17α_hydroxyprogesterone_comment_code', 'androstenedione_ng_dl',
       'androstenedione_nmol_l', 'androstenedione_comment_code',
       'anti_mullerian_hormone_ng_ml', 'anti_mullerian_hormone_pmol_l',
       'anti_mullerian_hormone_comment_code', 'estradiol_pg_ml',
       'estradiol_pmol_l', 'estradiol_comment_code', 'estrone_ng_dl',
       'estrone_pmol_l', 'estrone_comment_code', 'estrone_sulfate_pg_ml',
       'estrone_sulfate_pmol_l', 'estrone_sulfate_comment_code',
       'follicle_stimulating_hormone_miu_ml', 'fsh_comment_code',
       'luteinizing_hormone_miu_ml', 'luteinizing_hormone_comment_code',
       'progesterone_ng_dl', 'progesterone_nmol_l',
       'progesterone_comment_code', 'shbg_nmol_l', 'shbg_comment_code'],
      dtype='object')

In [6]:
df = df.drop(['education_level',
       'marital_status', 'family_income_poverty', 'weight_kg',
       'weight_comment', 'recumbent_length_cm', 'standing_height',
       'standing_height_comment','bmi_category_child', 'upper_leg_cm',
       'upper_arm_cm', 'arm_circumference_cm', 'waist_circ_cm', 'hip_circ_cm',
       'Unnamed: 0', '17α_hydroxyprogesterone_nmol_l','17α_hydroxyprogesterone_comment_code',
       'androstenedione_nmol_l', 'androstenedione_comment_code', 'anti_mullerian_hormone_pmol_l',
       'anti_mullerian_hormone_comment_code', 'estradiol_pmol_l', 'estradiol_comment_code', 'estrone_pmol_l', 'estrone_comment_code', 'estrone_sulfate_pmol_l', 'estrone_sulfate_comment_code','fsh_comment_code','luteinizing_hormone_comment_code','progesterone_nmol_l',
       'progesterone_comment_code','shbg_comment_code'], axis=1)

In [7]:
df.head()

,participant_id,gender,age_year,race,bmi,17α_hydroxyprogesterone_ng_dl,androstenedione_ng_dl,anti_mullerian_hormone_ng_ml,estradiol_pg_ml,estrone_ng_dl,estrone_sulfate_pg_ml,follicle_stimulating_hormone_miu_ml,luteinizing_hormone_miu_ml,progesterone_ng_dl,shbg_nmol_l
0,109266.0,2.0,29.0,6.0,37.8,27.1,93.1,1.65,35.5,4.53,NaN,7.15,4.55,1.500,22.54
1,109270.0,2.0,11.0,4.0,30.9,NaN,52.3,1.93,31.3,2.65,711.0,4.87,3.64,0.608,23.68
2,109271.0,1.0,49.0,3.0,29.7,114.0,166.0,NaN,69.6,14.90,273.0,8.30,18.86,8.770,42.91
3,109273.0,1.0,36.0,3.0,21.9,164.0,91.7,NaN,23.4,2.58,267.0,3.33,4.22,16.000,59.72
4,109274.0,1.0,68.0,7.0,30.2,74.6,46.8,NaN,36.3,4.31,303.0,5.14,9.47,4.110,62.92

In [8]:
df.describe()

,participant_id,gender,age_year,race,bmi,17α_hydroxyprogesterone_ng_dl,androstenedione_ng_dl,anti_mullerian_hormone_ng_ml,estradiol_pg_ml,estrone_ng_dl,estrone_sulfate_pg_ml,follicle_stimulating_hormone_miu_ml,luteinizing_hormone_miu_ml,progesterone_ng_dl,shbg_nmol_l
count,9445.000000,9445.000000,9445.000000,9445.000000,9411.000000,8153.000000,9435.000000,4635.000000,9104.000000,9086.000000,8922.000000,9029.000000,9125.000000,9387.000000,9087.000000
mean,117082.408258,1.511276,40.974801,3.433986,28.091574,65.945709,74.624907,1.426751,69.663630,5.204874,779.861483,18.634112,12.450835,100.013570,51.998016
std,4491.820218,0.499899,22.814214,1.612376,7.988300,63.685288,51.857873,2.096566,542.271437,18.716788,1224.052898,27.643886,14.476501,573.839339,43.661451
min,109266.000000,1.000000,6.000000,1.000000,12.600000,0.290000,0.580000,0.020000,1.220000,0.091900,1.440000,0.210000,0.070000,0.608000,0.830000
25%,113188.000000,1.000000,19.000000,3.000000,22.600000,24.000000,40.800000,0.020000,8.080000,2.110000,210.000000,3.220000,3.800000,2.530000,27.460000
50%,117054.000000,2.000000,41.000000,3.000000,27.100000,48.700000,63.600000,0.370000,22.400000,3.370000,475.500000,5.740000,6.630000,4.500000,41.100000
75%,121001.000000,2.000000,61.000000,4.000000,32.400000,85.800000,95.800000,2.260000,37.700000,5.180000,910.000000,17.430000,14.980000,8.515000,63.020000
max,124822.000000,2.000000,80.000000,7.000000,92.300000,1110.000000,649.000000,30.690000,15300.000000,497.000000,24900.000000,187.700000,150.300000,16200.000000,895.500000