### SHBG and BMI Association

Among adult males aged 20-49, are quartiles of serum SHBG associated with odds of obesity, adjusting for age, race/ethnicity, and physical activity?

* **Sex Hormone Binding Globulin (SHBG) nmol/L** from LabCorp
    * Male:
        * 20-49 y/o: 16.5 - 55.9 
        * '>' 49 y/o: 19.3 - 76.4
    * Female:
        * 20-49 y/o: 24.6 - 122
        * '>' 49 y/o: 17.3 - 125
        
This analysis will focus on the male adult population. It is a cross sectional study to see whether SHBG is associated with BMI in a meaningful way. 

**Binary obesity allows me to compare the prealence and estimate the odds of obesity across SHBG quartiles, making it easier to interpret differences in risk between exposure groups.**

Quartiles allows detection of:
* monotonic trneds (increasing/decreasing risk)
* thresholds (i.e. sudden jump in Q4)
* non-linear patterns

It also is less precise, however, it allows for a more intuitive interpretability and robustness of the results (?)

Quartiles test whether the outcome differs meaningfully across ordered exposure groups without assuming linearity. 

**Using quartiles allows me to examine whether the risk of obesity changes across ordered levels of SHBG without assuming a linear relationship. It also makes patterns easier to interpret and helps detect threshold or non-linear effects.**

Quartile analysis allows detection of non-linear relationship:
* threshold effects
* U-shapes
* plateaus

**Probability**: out of everyone, how many have the outcome?

**Odds**: compared to not having the outcome, how many do?

In [2]:
pip install psycopg2-binary sqlalchemy pandas

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp310-cp310-macosx_10_9_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /Users/Rachel/anaconda3/lib/python3.10/site-packages (1.4.39)
Requirement already satisfied: pandas in /Users/Rachel/anaconda3/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: greenlet!=0.4.17 in /Users/Rachel/anaconda3/lib/python3.10/site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/Rachel/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/Rachel/anaconda3/lib/python3.10/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /Users/Rachel/anaconda3/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /Users/Rachel/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Downloading psycopg2_binary-2.9.12-cp310-cp310-macosx_10_9_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 9.9 MB/s  0:00:00m eta 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
from sqlalchemy import create_engine

# Create engine and connect
engine = create_engine('postgresql://postgres:rsc@localhost:5432/NHANES_20172020')

# Query into a DataFrame
df_a = pd.read_csv('cleaned_anthropometry.csv')
df_a.to_sql("anthropometry", engine, if_exists='replace',index=False)

107

In [8]:
df_a.head()

,participant_id,weight_kg,weight_comment,recumbent_length_cm,standing_height,standing_height_comment,bmi,bmi_category_child,upper_leg_cm,upper_arm_cm,arm_circumference_cm,waist_circ_cm,hip_circ_cm
0,109264.0,42.2,NaN,NaN,154.7,NaN,17.6,2.0,36.3,33.8,22.7,63.8,85.0
1,109265.0,12.0,NaN,91.6,89.3,NaN,15.0,2.0,NaN,18.6,14.8,41.2,NaN
2,109266.0,97.1,NaN,NaN,160.2,NaN,37.8,NaN,40.8,34.7,35.8,117.9,126.1
3,109269.0,13.6,NaN,90.9,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,109270.0,75.3,NaN,NaN,156.0,NaN,30.9,4.0,42.6,36.1,31.0,91.4,NaN

In [12]:
df_d = pd.read_csv('cleaned_demographics.csv')
df_d.to_sql("demographics", engine, if_exists='replace',index=False)
df_h = pd.read_csv('clean_sex_horm.csv')
df_h.to_sql("sex_hormones", engine, if_exists='replace',index=False)

541

In [13]:
df_d.head()

,participant_id,gender,age_year,race,education_level,marital_status,family_income_poverty
0,109263.0,1.0,2.0,6.0,NaN,NaN,4.66
1,109264.0,2.0,13.0,1.0,NaN,NaN,0.83
2,109265.0,1.0,2.0,3.0,NaN,NaN,3.06
3,109266.0,2.0,29.0,6.0,5.0,3.0,5.00
4,109269.0,1.0,2.0,2.0,NaN,NaN,0.96

In [14]:
df_h.head()

,Unnamed: 0,participant_id,17α_hydroxyprogesterone_ng_dl,17α_hydroxyprogesterone_nmol_l,17α_hydroxyprogesterone_comment_code,androstenedione_ng_dl,androstenedione_nmol_l,androstenedione_comment_code,anti_mullerian_hormone_ng_ml,anti_mullerian_hormone_pmol_l,...,estrone_sulfate_comment_code,follicle_stimulating_hormone_miu_ml,fsh_comment_code,luteinizing_hormone_miu_ml,luteinizing_hormone_comment_code,progesterone_ng_dl,progesterone_nmol_l,progesterone_comment_code,shbg_nmol_l,shbg_comment_code
0,1,109266.0,27.1,0.821,0.0,93.1,3.25,0.0,1.65,11.78,...,NaN,7.15,0.0,4.55,0.0,1.500,0.0477,0.0,22.54,0.0
1,2,109270.0,NaN,NaN,NaN,52.3,1.83,0.0,1.93,13.78,...,0.0,4.87,0.0,3.64,0.0,0.608,0.0193,1.0,23.68,0.0
2,3,109271.0,114.0,3.450,0.0,166.0,5.79,0.0,NaN,NaN,...,0.0,8.30,0.0,18.86,0.0,8.770,0.2790,0.0,42.91,0.0
3,4,109273.0,164.0,4.970,0.0,91.7,3.20,0.0,NaN,NaN,...,0.0,3.33,0.0,4.22,0.0,16.000,0.5090,0.0,59.72,0.0
4,5,109274.0,74.6,2.260,0.0,46.8,1.63,0.0,NaN,NaN,...,0.0,5.14,0.0,9.47,0.0,4.110,0.1310,0.0,62.92,0.0

In [16]:
df_h = df_h.drop('Unnamed: 0',axis=1)

In [17]:
df_h.columns

Index(['participant_id', '17α_hydroxyprogesterone_ng_dl',
       '17α_hydroxyprogesterone_nmol_l',
       '17α_hydroxyprogesterone_comment_code', 'androstenedione_ng_dl',
       'androstenedione_nmol_l', 'androstenedione_comment_code',
       'anti_mullerian_hormone_ng_ml', 'anti_mullerian_hormone_pmol_l',
       'anti_mullerian_hormone_comment_code', 'estradiol_pg_ml',
       'estradiol_pmol_l', 'estradiol_comment_code', 'estrone_ng_dl',
       'estrone_pmol_l', 'estrone_comment_code', 'estrone_sulfate_pg_ml',
       'estrone_sulfate_pmol_l', 'estrone_sulfate_comment_code',
       'follicle_stimulating_hormone_miu_ml', 'fsh_comment_code',
       'luteinizing_hormone_miu_ml', 'luteinizing_hormone_comment_code',
       'progesterone_ng_dl', 'progesterone_nmol_l',
       'progesterone_comment_code', 'shbg_nmol_l', 'shbg_comment_code'],
      dtype='object')

In [23]:
%reload_ext sql

In [88]:
%sql DROP TABLE hormone_dataset_m;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

++
||
++
++

In [89]:
%%sql

CREATE TABLE hormone_dataset_m AS
SELECT d.participant_id,
    d.gender,
    d.age_year,
    d.race,
    a.bmi,
    s.shbg_nmol_l,
    -- obesity flag
    CASE
        WHEN a.bmi >= 30 THEN 1
        ELSE 0
    END AS obese,
    
    -- SHBG quartiles
    NTILE(4) OVER (ORDER BY s.shbg_nmol_l) AS shbg_quartile
    
FROM demographics d
JOIN anthropometry a
    ON d.participant_id = a.participant_id
JOIN sex_hormones s
    ON d.participant_id = s.participant_id
WHERE d.age_year BETWEEN 20 AND 49
    AND d.gender = 1;
    
CREATE TABLE hormone_dataset_f AS
SELECT d.participant_id,
    d.gender,
    d.age_year,
    d.race,
    a.bmi,
    s.shbg_nmol_l,
    -- obesity flag
    CASE
        WHEN a.bmi >= 30 THEN 1
        ELSE 0
    END AS obese,
    
    -- SHBG quartiles
    NTILE(4) OVER (ORDER BY s.shbg_nmol_l) AS shbg_quartile
    
FROM demographics d
JOIN anthropometry a
    ON d.participant_id = a.participant_id
JOIN sex_hormones s
    ON d.participant_id = s.participant_id
WHERE d.age_year BETWEEN 20 AND 49
    AND d.gender = 2;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

1457 rows affected.

1706 rows affected.

++
||
++
++

#### Male Cohort

In [90]:
%%sql

SELECT *
FROM hormone_dataset_m
LIMIT 15;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

15 rows affected.

+----------------+--------+----------+------+------+-------------+-------+---------------+
| participant_id | gender | age_year | race | bmi  | shbg_nmol_l | obese | shbg_quartile |
+----------------+--------+----------+------+------+-------------+-------+---------------+
|    110753.0    |  1.0   |   36.0   | 2.0  | 29.4 |     2.54    |   0   |       1       |
|    124616.0    |  1.0   |   28.0   | 6.0  | 35.4 |     4.33    |   1   |       1       |
|    112509.0    |  1.0   |   35.0   | 6.0  | 40.1 |     5.01    |   1   |       1       |
|    118319.0    |  1.0   |   27.0   | 2.0  | 33.9 |     6.36    |   1   |       1       |
|    121997.0    |  1.0   |   24.0   | 2.0  | 42.3 |     6.43    |   1   |       1       |
|    112693.0    |  1.0   |   20.0   | 1.0  | 28.8 |     7.01    |   0   |       1       |
|    124383.0    |  1.0   |   33.0   | 3.0  | 36.4 |     7.15    |   1   |       1       |
|    119958.0    |  1.0   |   30.0   | 3.0  | 44.9 |     7.22    |   1   |       1       |
|    112634.0    |  1.0   |   42.0   | 6.0  | 34.2 |     7.5     |   1   |       1       |
|    114614.0    |  1.0   |   37.0   | 6.0  | 35.2 |     7.55    |   1   |       1       |
+----------------+--------+----------+------+------+-------------+-------+---------------+
Truncated to displaylimit of 10.

In [91]:
%sql SELECT COUNT(*) FROM hormone_dataset_m;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

1 rows affected.

+-------+
| count |
+-------+
|  1457 |
+-------+

In [92]:
%%sql

SELECT MIN(age_year), MAX(age_year)
FROM hormone_dataset_m;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

1 rows affected.

+------+------+
| min  | max  |
+------+------+
| 20.0 | 49.0 |
+------+------+

In [93]:
%%sql

SELECT shbg_quartile, COUNT(*)
FROM hormone_dataset_m
GROUP BY shbg_quartile
ORDER BY shbg_quartile;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

4 rows affected.

+---------------+-------+
| shbg_quartile | count |
+---------------+-------+
|       1       |  365  |
|       2       |  364  |
|       3       |  364  |
|       4       |  364  |
+---------------+-------+

In [94]:
%%sql

SELECT obese,
    COUNT (participant_id)
FROM hormone_dataset_m
GROUP BY obese;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

2 rows affected.

+-------+-------+
| obese | count |
+-------+-------+
|   0   |  866  |
|   1   |  591  |
+-------+-------+

In [96]:
%%sql

SELECT
    shbg_quartile,
    COUNT(*) AS n,
    AVG(obese::int) AS obesity_rate
FROM hormone_dataset_m
GROUP BY shbg_quartile
ORDER BY shbg_quartile;

-- this result is for the male cohort only

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

4 rows affected.

+---------------+-----+------------------------+
| shbg_quartile |  n  |      obesity_rate      |
+---------------+-----+------------------------+
|       1       | 365 | 0.59726027397260273973 |
|       2       | 364 | 0.46153846153846153846 |
|       3       | 364 | 0.35164835164835164835 |
|       4       | 364 | 0.21153846153846153846 |
+---------------+-----+------------------------+

In [99]:
%%sql

SELECT 
    shbg_quartile,
    COUNT(*) AS n,
    AVG(age_year::int) AS age,
    AVG(bmi::int) AS bmi
FROM hormone_dataset_m
GROUP BY shbg_quartile
ORDER BY shbg_quartile;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

4 rows affected.

+---------------+-----+---------------------+---------------------+
| shbg_quartile |  n  |         age         |         bmi         |
+---------------+-----+---------------------+---------------------+
|       1       | 365 | 33.4767123287671233 | 32.9424657534246575 |
|       2       | 364 | 34.5302197802197802 | 30.4725274725274725 |
|       3       | 364 | 35.6373626373626374 | 28.8250000000000000 |
|       4       | 364 | 36.3186813186813187 | 26.3928571428571429 |
+---------------+-----+---------------------+---------------------+

In [100]:
df_m = pd.read_sql("SELECT * FROM hormone_dataset_m", engine)

In [101]:
df_m.describe()

,participant_id,gender,age_year,race,bmi,shbg_nmol_l,obese,shbg_quartile
count,1457.000000,1457.0,1457.000000,1457.000000,1453.000000,1451.000000,1457.000000,1457.000000
mean,117162.098833,1.0,34.989705,3.448868,29.655196,29.939083,0.405628,2.498970
std,4559.979745,0.0,8.706952,1.703350,6.995822,14.520278,0.491182,1.118724
min,109271.000000,1.0,20.000000,1.000000,16.300000,2.540000,0.000000,1.000000
25%,113120.000000,1.0,28.000000,2.000000,24.900000,19.950000,0.000000,1.000000
50%,117170.000000,1.0,35.000000,3.000000,28.500000,27.170000,0.000000,2.000000
75%,121169.000000,1.0,43.000000,4.000000,33.300000,36.695000,1.000000,3.000000
max,124818.000000,1.0,49.000000,7.000000,86.200000,153.800000,1.000000,4.000000

In [112]:
df_m.dtypes

participant_id    float64
gender            float64
age_year          float64
race              float64
bmi               float64
shbg_nmol_l       float64
obese               int64
shbg_quartile       int64
dtype: object

In [103]:
df_m.isna().sum()

#there are 10 SHBG values missing out of 3164 rows and 7 bmi values missing. the null values will be dropped

participant_id    0
gender            0
age_year          0
race              0
bmi               4
shbg_nmol_l       6
obese             0
shbg_quartile     0
dtype: int64

In [117]:
df_m = df_m.dropna()

In [105]:
df_m.shape

(1447, 8)

In [113]:
df_m = pd.get_dummies(df_m, columns=['race'], drop_first=True)

In [106]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [120]:
y = df_m['obese']

X = df_m[['shbg_quartile',
        'age_year'
       ]]

In [121]:
race_cols = [col for col in df_m.columns if 'race' in col]
X = pd.concat([X, df_m[race_cols]], axis=1)

In [122]:
X = sm.add_constant(X)

In [123]:
model = sm.Logit(y,X)
result = model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.593240
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  obese   No. Observations:                 1447
Model:                          Logit   Df Residuals:                     1439
Method:                           MLE   Df Model:                            7
Date:                Mon, 27 Apr 2026   Pseudo R-squ.:                  0.1214
Time:                        16:56:50   Log-Likelihood:                -858.42
converged:                       True   LL-Null:                       -977.08
Covariance Type:            nonrobust   LLR p-value:                 1.384e-47
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.3702      0.281      1.316      0.188      -0.181       0.922
shbg_quartile    -0.6870      0.057    -12.107      0.000      -0.798      -0.576
age_year          0.0351      0.007      5.113      0.000       0.022       0.049
race_2.0         -0.5507      0.226     -2.439      0.015      -0.993      -0.108
race_3.0         -0.1017      0.176     -0.576      0.564      -0.447       0.244
race_4.0         -0.0858      0.189     -0.455      0.649      -0.456       0.284
race_6.0         -1.9062      0.257     -7.420      0.000      -2.410      -1.403
race_7.0         -0.1217      0.261     -0.466      0.641      -0.634       0.390
=================================================================================